#!/usr/bin/env python3
"""
Daily XAUUSD Trading Analysis Pipeline
=======================================
This script runs the complete workflow:
1. Generate LSTM price prediction model and save image
2. Generate technical analysis chart (EMA + MACD)
3. Use Gemini API to analyze both images
4. Send trading recommendation to LINE

Usage:
    python daily_trading_pipeline.py
"""

import os
import sys
import subprocess
import json
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Add ml-models directory to path
ML_MODELS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(ML_MODELS_DIR)
sys.path.insert(0, os.path.join(PROJECT_ROOT, 'backend', 'src'))

DATA_DIR = os.path.join(PROJECT_ROOT, 'backend', 'data')
PREDICTIONS_DIR = os.path.join(DATA_DIR, 'predictions')
GRAPHS_DIR = os.path.join(DATA_DIR, 'graphs')

# Debug: Print paths
print(f"DEBUG: ML_MODELS_DIR = {ML_MODELS_DIR}")
print(f"DEBUG: PROJECT_ROOT = {PROJECT_ROOT}")
print(f"DEBUG: PREDICTIONS_DIR = {PREDICTIONS_DIR}")
print(f"DEBUG: GRAPHS_DIR = {GRAPHS_DIR}")

# Create directories if they don't exist
os.makedirs(PREDICTIONS_DIR, exist_ok=True)
os.makedirs(GRAPHS_DIR, exist_ok=True)

def log_pipeline(message):
    """Log message with timestamp"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] {message}")

def run_step(step_name, script_path):
    """
    Run a Python script and return the result
    
    Args:
        step_name: Name of the step
        script_path: Path to the Python script
    
    Returns:
        bool: True if successful, False otherwise
    """
    try:
        log_pipeline(f"Starting: {step_name}")
        
        if not os.path.exists(script_path):
            log_pipeline(f"ERROR: Script not found: {script_path}")
            return False
        
        # Run the script
        result = subprocess.run(
            [sys.executable, script_path],
            cwd=ML_MODELS_DIR,
            capture_output=True,
            text=True,
            timeout=600  # 10 minutes timeout
        )
        
        # Print output
        if result.stdout:
            print(result.stdout)
        
        if result.stderr:
            print(f"Warnings/Errors:\n{result.stderr}")
        
        if result.returncode != 0:
            log_pipeline(f"ERROR in {step_name}: Return code {result.returncode}")
            return False
        
        log_pipeline(f"Completed: {step_name}")
        return True
        
    except subprocess.TimeoutExpired:
        log_pipeline(f"ERROR: {step_name} timed out after 10 minutes")
        return False
    except Exception as e:
        log_pipeline(f"ERROR in {step_name}: {str(e)}")
        return False

def get_latest_prediction_image():
    """Get the latest prediction image"""
    try:
        prediction_files = sorted(
            Path(PREDICTIONS_DIR).glob('xauusd_prediction_*.png'),
            key=lambda x: x.stat().st_mtime,
            reverse=True
        )
        if prediction_files:
            return str(prediction_files[0])
    except Exception as e:
        log_pipeline(f"Error getting prediction image: {e}")
    return None

def get_latest_graph_image():
    """Get the latest graph image"""
    try:
        graph_files = sorted(
            Path(GRAPHS_DIR).glob('xauusd_graph_*.png'),
            key=lambda x: x.stat().st_mtime,
            reverse=True
        )
        if graph_files:
            return str(graph_files[0])
    except Exception as e:
        log_pipeline(f"Error getting graph image: {e}")
    return None

def send_to_both_platforms(analysis_text, prediction_image_path):
    """
    Send analysis to both LINE and Telegram using the unified broadcaster
    
    Args:
        analysis_text: Text analysis from Gemini
        prediction_image_path: Path to prediction image
    """
    try:
        import subprocess
        
        # Call the unified broadcaster script
        broadcaster_script = os.path.join(ML_MODELS_DIR, 'send_to_both_platforms.py')
        
        # We'll use a simpler approach - directly import and call the functions
        # This avoids subprocess complexity
        log_pipeline("Sending to LINE and Telegram...")
        
        # Import the broadcaster functions
        import sys
        sys.path.insert(0, ML_MODELS_DIR)
        
        # Send to LINE
        try:
            from services.lineNotifier import LineNotifier
            notifier = LineNotifier()
            message = f"""📊 XAUUSD Trading Analysis - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{analysis_text}

---
Generated by: AI Trading Bot"""
            
            success = notifier.sendMessage(message)
            if success:
                log_pipeline("✅ LINE: Message sent successfully")
            else:
                log_pipeline("⚠️ LINE: Failed to send message")
        except Exception as e:
            log_pipeline(f"⚠️ LINE: Error - {e}")
        
        # Send to Telegram
        try:
            import requests
            telegram_token = os.getenv('TELEGRAM_BOT_TOKEN')
            telegram_user_id = os.getenv('TELEGRAM_USER_ID')
            
            if telegram_token and telegram_user_id:
                # Send text message first
                telegram_message = f"""<b>📊 XAUUSD Trading Analysis</b>
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{analysis_text}

---
<i>Generated by: AI Trading Bot</i>"""
                
                url = f'https://api.telegram.org/bot{telegram_token}/sendMessage'
                response = requests.post(url, json={
                    'chat_id': telegram_user_id,
                    'text': telegram_message,
                    'parse_mode': 'HTML'
                }, timeout=10)
                
                if response.status_code == 200:
                    log_pipeline("✅ Telegram: Message sent successfully")
                else:
                    log_pipeline(f"⚠️ Telegram: Failed ({response.status_code})")
                
                # Send prediction image
                try:
                    with open(prediction_image_path, 'rb') as photo:
                        url = f'https://api.telegram.org/bot{telegram_token}/sendPhoto'
                        response = requests.post(url, 
                            files={'photo': photo},
                            data={
                                'chat_id': telegram_user_id,
                                'caption': '📊 XAUUSD Price Prediction'
                            },
                            timeout=15
                        )
                    
                    if response.status_code == 200:
                        log_pipeline("✅ Telegram: Prediction image sent")
                    else:
                        log_pipeline(f"⚠️ Telegram: Image failed ({response.status_code})")
                except Exception as img_error:
                    log_pipeline(f"⚠️ Telegram: Image error - {img_error}")
                
                # Send graph image
                try:
                    graph_img = get_latest_graph_image()
                    if graph_img:
                        with open(graph_img, 'rb') as photo:
                            url = f'https://api.telegram.org/bot{telegram_token}/sendPhoto'
                            response = requests.post(url,
                                files={'photo': photo},
                                data={
                                    'chat_id': telegram_user_id,
                                    'caption': '📈 Technical Analysis Chart'
                                },
                                timeout=15
                            )
                        
                        if response.status_code == 200:
                            log_pipeline("✅ Telegram: Graph image sent")
                        else:
                            log_pipeline(f"⚠️ Telegram: Graph failed ({response.status_code})")
                except Exception as graph_error:
                    log_pipeline(f"⚠️ Telegram: Graph error - {graph_error}")
                    
            else:
                log_pipeline("⏭️ Telegram: Skipped (credentials not configured)")
        except Exception as e:
            log_pipeline(f"⚠️ Telegram: Error - {e}")
        
    except Exception as e:
        log_pipeline(f"ERROR in broadcasting: {e}")

def main():
    """Main pipeline orchestration"""
    print("\n" + "="*80)
    print("XAUUSD Daily Trading Analysis Pipeline")
    print("="*80)
    log_pipeline("Pipeline started")
    
    # Step 1: Generate LSTM price prediction
    log_pipeline("Step 1/3: Generating LSTM price prediction model...")
    prediction_script = os.path.join(ML_MODELS_DIR, 'model_price_prediction_genarating_img.py')
    step1_success = run_step("LSTM Price Prediction", prediction_script)
    
    if not step1_success:
        log_pipeline("Pipeline failed at Step 1")
        return False
    
    # Step 2: Generate technical analysis chart
    log_pipeline("Step 2/3: Generating technical analysis chart...")
    graph_script = os.path.join(ML_MODELS_DIR, 'graph_xauusd_model.py')
    step2_success = run_step("Technical Analysis Chart", graph_script)
    
    if not step2_success:
        log_pipeline("Pipeline failed at Step 2")
        return False
    
    # Step 3: Analyze images with Gemini and send notifications
    log_pipeline("Step 3/3: Analyzing images with Gemini AI...")
    
    prediction_img = get_latest_prediction_image()
    graph_img = get_latest_graph_image()
    
    if not prediction_img:
        log_pipeline("WARNING: No prediction image found, will send text-only message")
        # Send text-only fallback message
        fallback_message = f"""⚠️ XAUUSD Daily Analysis (Image generation in progress)

Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

The prediction model is currently running. Analysis will be available shortly.

Please check back in a few minutes for the complete analysis with charts.
"""
        send_to_both_platforms(fallback_message, None)
        log_pipeline("Pipeline completed with fallback message")
        return True
    
    if not graph_img:
        log_pipeline("WARNING: No graph image found, continuing with prediction image only")
    
    log_pipeline(f"Found prediction image: {prediction_img}")
    if graph_img:
        log_pipeline(f"Found graph image: {graph_img}")
    
    # Call Gemini API
    try:
        from gemini_api_price_prediction import get_image_explanation
        analysis = get_image_explanation(prediction_img, graph_img)
        log_pipeline("Successfully received analysis from Gemini API")
        
        # Send to both LINE and Telegram
        log_pipeline("Broadcasting analysis to LINE and Telegram...")
        send_to_both_platforms(analysis, prediction_img)
        
        log_pipeline("Pipeline completed successfully!")
        return True
        
    except Exception as e:
        log_pipeline(f"ERROR calling Gemini API: {e}")
        # Send fallback message with error
        fallback_message = f"""⚠️ XAUUSD Daily Analysis (AI Analysis Unavailable)

Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Charts have been generated successfully, but AI analysis is temporarily unavailable.

Error: {str(e)[:100]}

Please refer to the charts for technical analysis.
"""
        send_to_both_platforms(fallback_message, prediction_img)
        return False
    
    print("\n" + "="*80)
    log_pipeline("Pipeline completed successfully!")
    print("="*80)
    
    # Save pipeline summary
    summary = {
        "timestamp": datetime.now().isoformat(),
        "status": "success",
        "prediction_image": prediction_img,
        "graph_image": graph_img,
        "analysis": analysis if 'analysis' in locals() else None
    }
    
    summary_path = os.path.join(DATA_DIR, 'pipeline_summary.json')
    try:
        with open(summary_path, 'w', encoding='utf-8') as f:
            json.dump(summary, f, ensure_ascii=False, indent=2)
        log_pipeline(f"Summary saved to: {summary_path}")
    except Exception as e:
        log_pipeline(f"WARNING: Could not save summary: {e}")
    
    return True

if __name__ == "__main__":
    try:
        success = main()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        log_pipeline("Pipeline interrupted by user")
        sys.exit(130)
    except Exception as e:
        log_pipeline(f"FATAL ERROR: {e}")
        sys.exit(1)
