#!/usr/bin/env python3
"""
Daily XAUUSD Trading Analysis Pipeline
=======================================
This script runs the complete workflow:
1. Generate LSTM price prediction model and save image
2. Generate technical analysis chart (EMA + MACD)
3. Use Gemini API to analyze both images
4. Send trading recommendation to LINE

Usage:
    python daily_trading_pipeline.py
"""

import os
import sys
import subprocess
import json
from datetime import datetime
from pathlib import Path

# Add ml-models directory to path
ML_MODELS_DIR = os.path.dirname(__file__)
PROJECT_ROOT = os.path.dirname(os.path.dirname(ML_MODELS_DIR))
sys.path.insert(0, os.path.join(PROJECT_ROOT, 'backend', 'src'))

DATA_DIR = os.path.join(PROJECT_ROOT, 'backend', 'data')
PREDICTIONS_DIR = os.path.join(DATA_DIR, 'predictions')
GRAPHS_DIR = os.path.join(DATA_DIR, 'graphs')

# Create directories if they don't exist
os.makedirs(PREDICTIONS_DIR, exist_ok=True)
os.makedirs(GRAPHS_DIR, exist_ok=True)

def log_pipeline(message):
    """Log message with timestamp"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] {message}")

def run_step(step_name, script_path):
    """
    Run a Python script and return the result
    
    Args:
        step_name: Name of the step
        script_path: Path to the Python script
    
    Returns:
        bool: True if successful, False otherwise
    """
    try:
        log_pipeline(f"Starting: {step_name}")
        
        if not os.path.exists(script_path):
            log_pipeline(f"ERROR: Script not found: {script_path}")
            return False
        
        # Run the script
        result = subprocess.run(
            [sys.executable, script_path],
            cwd=ML_MODELS_DIR,
            capture_output=True,
            text=True,
            timeout=600  # 10 minutes timeout
        )
        
        # Print output
        if result.stdout:
            print(result.stdout)
        
        if result.stderr:
            print(f"Warnings/Errors:\n{result.stderr}")
        
        if result.returncode != 0:
            log_pipeline(f"ERROR in {step_name}: Return code {result.returncode}")
            return False
        
        log_pipeline(f"Completed: {step_name}")
        return True
        
    except subprocess.TimeoutExpired:
        log_pipeline(f"ERROR: {step_name} timed out after 10 minutes")
        return False
    except Exception as e:
        log_pipeline(f"ERROR in {step_name}: {str(e)}")
        return False

def get_latest_prediction_image():
    """Get the latest prediction image"""
    try:
        prediction_files = sorted(
            Path(PREDICTIONS_DIR).glob('xauusd_prediction_*.png'),
            key=lambda x: x.stat().st_mtime,
            reverse=True
        )
        if prediction_files:
            return str(prediction_files[0])
    except Exception as e:
        log_pipeline(f"Error getting prediction image: {e}")
    return None

def get_latest_graph_image():
    """Get the latest graph image"""
    try:
        graph_files = sorted(
            Path(GRAPHS_DIR).glob('xauusd_graph_*.png'),
            key=lambda x: x.stat().st_mtime,
            reverse=True
        )
        if graph_files:
            return str(graph_files[0])
    except Exception as e:
        log_pipeline(f"Error getting graph image: {e}")
    return None

def send_to_line(analysis_text, prediction_image_path):
    """
    Send analysis and prediction image to LINE
    
    Args:
        analysis_text: Text analysis from Gemini
        prediction_image_path: Path to prediction image
    """
    try:
        from services.lineNotifier import LineNotifier
        
        notifier = LineNotifier()
        
        # Prepare message
        message = f"""
📊 XAUUSD Trading Analysis - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{analysis_text}

---
Generated by: AI Trading Bot
"""
        
        # Send text message
        log_pipeline("Sending text analysis to LINE...")
        success = notifier.sendMessage(message)
        
        if success:
            log_pipeline("Text message sent successfully to LINE")
        else:
            log_pipeline("WARNING: Failed to send text message to LINE")
        
        # Note: LINE API requires additional setup for image sending
        # This would require using FlexMessage or template messages
        # For now, the analysis text is sent
        
    except ImportError:
        log_pipeline("WARNING: LineNotifier not available. Skipping LINE notification.")
    except Exception as e:
        log_pipeline(f"ERROR sending to LINE: {e}")

def main():
    """Main pipeline orchestration"""
    print("\n" + "="*80)
    print("XAUUSD Daily Trading Analysis Pipeline")
    print("="*80)
    log_pipeline("Pipeline started")
    
    # Step 1: Generate LSTM price prediction
    log_pipeline("Step 1/3: Generating LSTM price prediction model...")
    prediction_script = os.path.join(ML_MODELS_DIR, 'model_price_prediction_genarating_img.py')
    step1_success = run_step("LSTM Price Prediction", prediction_script)
    
    if not step1_success:
        log_pipeline("Pipeline failed at Step 1")
        return False
    
    # Step 2: Generate technical analysis chart
    log_pipeline("Step 2/3: Generating technical analysis chart...")
    graph_script = os.path.join(ML_MODELS_DIR, 'graph_xauusd_model.py')
    step2_success = run_step("Technical Analysis Chart", graph_script)
    
    if not step2_success:
        log_pipeline("Pipeline failed at Step 2")
        return False
    
    # Step 3: Analyze images with Gemini and send to LINE
    log_pipeline("Step 3/3: Analyzing images with Gemini AI...")
    
    # Get the latest images
    prediction_img = get_latest_prediction_image()
    graph_img = get_latest_graph_image()
    
    if not prediction_img:
        log_pipeline("ERROR: No prediction image found")
        return False
    
    if not graph_img:
        log_pipeline("ERROR: No graph image found")
        return False
    
    log_pipeline(f"Using prediction image: {prediction_img}")
    log_pipeline(f"Using graph image: {graph_img}")
    
    try:
        from gemini_api_price_prediction import main as gemini_main
        
        analysis = gemini_main(prediction_img, graph_img)
        
        if analysis:
            log_pipeline("Successfully received analysis from Gemini API")
            print("\n" + "="*80)
            print("GEMINI ANALYSIS:")
            print("="*80)
            print(analysis)
            
            # Send to LINE
            log_pipeline("Sending analysis and images to LINE...")
            send_to_line(analysis, prediction_img)
            
        else:
            log_pipeline("ERROR: Failed to get analysis from Gemini")
            return False
            
    except Exception as e:
        log_pipeline(f"ERROR in Step 3: {e}")
        return False
    
    print("\n" + "="*80)
    log_pipeline("Pipeline completed successfully!")
    print("="*80)
    
    # Save pipeline summary
    summary = {
        "timestamp": datetime.now().isoformat(),
        "status": "success",
        "prediction_image": prediction_img,
        "graph_image": graph_img,
        "analysis": analysis if 'analysis' in locals() else None
    }
    
    summary_path = os.path.join(DATA_DIR, 'pipeline_summary.json')
    try:
        with open(summary_path, 'w', encoding='utf-8') as f:
            json.dump(summary, f, ensure_ascii=False, indent=2)
        log_pipeline(f"Summary saved to: {summary_path}")
    except Exception as e:
        log_pipeline(f"WARNING: Could not save summary: {e}")
    
    return True

if __name__ == "__main__":
    try:
        success = main()
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        log_pipeline("Pipeline interrupted by user")
        sys.exit(130)
    except Exception as e:
        log_pipeline(f"FATAL ERROR: {e}")
        sys.exit(1)
