#!/usr/bin/env python3
"""
Send Gemini Analysis to LINE with Images (uploaded to Imgur)
"""

import os
import sys
import json
import requests
from pathlib import Path
from datetime import datetime

# Get project root and latest images
project_root = Path(__file__).parent.parent
predictions_dir = project_root / 'backend' / 'data' / 'predictions'
graphs_dir = project_root / 'backend' / 'data' / 'graphs'

print("="*80)
print("XAUUSD Trading Analysis - Send to LINE")
print("="*80)

# Step 0: Upload images to Imgur (so LINE can access them via HTTPS)
def upload_to_imgur(image_path, imgur_client_id):
    """Upload image to Imgur and return the public URL"""
    try:
        with open(image_path, 'rb') as f:
            files = {'image': f}
            headers = {'Authorization': f'Client-ID {imgur_client_id}'}
            response = requests.post(
                'https://api.imgur.com/3/image',
                files=files,
                headers=headers,
                timeout=30
            )
        
        if response.status_code == 200:
            data = response.json()
            url = data['data']['link']
            print(f"  [OK] Uploaded: {url}")
            return url
        else:
            print(f"  [ERROR] Imgur upload failed: {response.status_code}")
            return None
    except Exception as e:
        print(f"  [ERROR] {e}")
        return None

print("\n[0] Loading configuration...")
try:
    from dotenv import load_dotenv
    dotenv_path = project_root / '.env'
    load_dotenv(dotenv_path)
    
    imgur_client_id = os.getenv('IMGUR_CLIENT_ID', '')
    
    if not imgur_client_id:
        print("[WARNING] IMGUR_CLIENT_ID not found in .env")
        print("[INFO] Using local file paths (images may not display)")
    
except Exception as e:
    print(f"[WARNING] {e}")
    imgur_client_id = ''

# Step 1: Get Gemini analysis
print("\n[1] Getting Gemini AI analysis...")
try:
    from gemini_api_price_prediction import main as gemini_main
    
    # Find latest images
    prediction_files = sorted(predictions_dir.glob('xauusd_prediction_*.png'), key=lambda x: x.stat().st_mtime, reverse=True)
    graph_files = sorted(graphs_dir.glob('xauusd_graph_*.png'), key=lambda x: x.stat().st_mtime, reverse=True)
    
    if not prediction_files or not graph_files:
        print("[ERROR] Images not found")
        sys.exit(1)
    
    prediction_img = str(prediction_files[0])
    graph_img = str(graph_files[0])
    
    print(f"[OK] Using prediction: {Path(prediction_img).name}")
    print(f"[OK] Using graph: {Path(graph_img).name}")
    
    analysis = gemini_main(prediction_img, graph_img)
    
    if not analysis:
        print("[ERROR] Failed to get Gemini analysis")
        sys.exit(1)
    
    print("[OK] Received Gemini analysis")
    
except Exception as e:
    print(f"[ERROR] {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

# Step 1b: Upload images to Imgur if client ID exists
print("\n[1b] Uploading images to Imgur...")
if imgur_client_id:
    print(f"  Uploading prediction image...")
    prediction_url = upload_to_imgur(prediction_img, imgur_client_id)
    
    print(f"  Uploading graph image...")
    graph_url = upload_to_imgur(graph_img, imgur_client_id)
else:
    print("  [SKIP] IMGUR_CLIENT_ID not set - using local paths")
    prediction_url = f'file://{prediction_img}'
    graph_url = f'file://{graph_img}'

# Step 2: Prepare message for LINE
print("\n[2] Preparing message for LINE...")

line_message = f"""XAUUSD Daily Trading Analysis
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{analysis}

---
Generated by: AI Trading Bot
Disclaimer: This analysis is based on historical data and may not reflect future price movements"""

# Step 3: Send to LINE
print("\n[3] Sending to LINE...")

try:
    # Load environment variables
    from dotenv import load_dotenv
    dotenv_path = project_root / '.env'
    load_dotenv(dotenv_path)
    
    line_token = os.getenv('LINE_CHANNEL_ACCESS_TOKEN')
    line_user_id = os.getenv('LINE_USER_ID')
    use_broadcast = os.getenv('USE_BROADCAST', 'true').lower() == 'true'
    
    if not line_token:
        print("[ERROR] LINE_CHANNEL_ACCESS_TOKEN not set in .env")
        sys.exit(1)
    
    # Prepare messages with both text and images
    messages = [
        {
            'type': 'text',
            'text': line_message
        }
    ]
    
    # Note: Images require Imgur upload (set IMGUR_CLIENT_ID in .env)
    # For now, sending text analysis only
    
    # Send as Push message (if user_id exists) or Broadcast
    if line_user_id and not use_broadcast:
        # Send to specific user
        url = 'https://api.line.me/v2/bot/message/push'
        data = {
            'to': line_user_id,
            'messages': messages
        }
        print(f"  Sending to user: {line_user_id}")
    else:
        # Broadcast to all followers
        url = 'https://api.line.me/v2/bot/message/broadcast'
        data = {
            'messages': messages
        }
        print("  Sending as Broadcast to all followers")
    
    headers = {
        'Content-Type': 'application/json',
        'Authorization': f'Bearer {line_token}'
    }
    
    response = requests.post(url, json=data, headers=headers)
    
    if response.status_code == 200:
        print("[OK] Message sent to LINE successfully!")
        print(f"  Status: {response.status_code}")
        
        # Save summary
        summary = {
            'timestamp': datetime.now().isoformat(),
            'status': 'success',
            'method': 'broadcast' if use_broadcast else 'push',
            'prediction_image': prediction_img,
            'graph_image': graph_img,
            'prediction_url': prediction_url,
            'graph_url': graph_url,
            'analysis_preview': analysis[:200] + '...' if len(analysis) > 200 else analysis,
            'line_response': response.status_code
        }
        
        summary_path = project_root / 'backend' / 'data' / 'line_notification_summary.json'
        with open(summary_path, 'w', encoding='utf-8') as f:
            json.dump(summary, f, ensure_ascii=False, indent=2)
        
        print(f"[OK] Summary saved to: {summary_path}")
        
    else:
        print(f"[ERROR] Failed to send to LINE")
        print(f"  Status: {response.status_code}")
        print(f"  Response: {response.text}")
        sys.exit(1)

except Exception as e:
    print(f"[ERROR] {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

print("\n" + "="*80)
if imgur_client_id:
    print("[OK] Analysis + Images sent to LINE successfully!")
else:
    print("[OK] Analysis sent to LINE (images require IMGUR_CLIENT_ID in .env)")
print("="*80)
