#!/usr/bin/env python3
"""
Send Gemini Analysis to Telegram
"""

import os
import sys
import json
import requests
from pathlib import Path
from datetime import datetime

# Get project root and latest images
project_root = Path(__file__).parent.parent
predictions_dir = project_root / 'backend' / 'data' / 'predictions'
graphs_dir = project_root / 'backend' / 'data' / 'graphs'

print("="*80)
print("XAUUSD Trading Analysis - Send to Telegram")
print("="*80)

print("\n[0] Loading configuration...")
try:
    from dotenv import load_dotenv
    dotenv_path = project_root / '.env'
    load_dotenv(dotenv_path)
    
except Exception as e:
    print(f"[WARNING] {e}")

# Step 1: Get Gemini analysis
print("\n[1] Getting Gemini AI analysis...")
try:
    from gemini_api_price_prediction import main as gemini_main
    
    # Find latest images
    prediction_files = sorted(predictions_dir.glob('xauusd_prediction_*.png'), key=lambda x: x.stat().st_mtime, reverse=True)
    graph_files = sorted(graphs_dir.glob('xauusd_graph_*.png'), key=lambda x: x.stat().st_mtime, reverse=True)
    
    if not prediction_files or not graph_files:
        print("[ERROR] Images not found")
        sys.exit(1)
    
    prediction_img = str(prediction_files[0])
    graph_img = str(graph_files[0])
    
    print(f"[OK] Using prediction: {Path(prediction_img).name}")
    print(f"[OK] Using graph: {Path(graph_img).name}")
    
    analysis = gemini_main(prediction_img, graph_img)
    
    if not analysis:
        print("[ERROR] Failed to get Gemini analysis")
        sys.exit(1)
    
    print("[OK] Received Gemini analysis")
    
except Exception as e:
    print(f"[ERROR] {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

# Step 2: Prepare message for Telegram
print("\n[2] Preparing message for Telegram...")

telegram_message = f"""<b>📊 XAUUSD Daily Trading Analysis</b>
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{analysis}

---
<i>Generated by: AI Trading Bot
Disclaimer: This analysis is based on historical data and may not reflect future price movements</i>"""

# Step 3: Send to Telegram
print("\n[3] Sending to Telegram...")

try:
    # Load environment variables
    from dotenv import load_dotenv
    dotenv_path = project_root / '.env'
    load_dotenv(dotenv_path)
    
    telegram_token = os.getenv('TELEGRAM_BOT_TOKEN')
    telegram_user_id = os.getenv('TELEGRAM_USER_ID')
    telegram_enabled = os.getenv('TELEGRAM_ENABLED', 'true').lower() == 'true'
    
    if not telegram_enabled:
        print("[INFO] Telegram is disabled in configuration")
        sys.exit(0)
    
    if not telegram_token:
        print("[ERROR] TELEGRAM_BOT_TOKEN not set in .env")
        sys.exit(1)
    
    if not telegram_user_id:
        print("[ERROR] TELEGRAM_USER_ID not set in .env")
        sys.exit(1)
    
    # Send message via Telegram Bot API
    url = f'https://api.telegram.org/bot{telegram_token}/sendMessage'
    
    data = {
        'chat_id': telegram_user_id,
        'text': telegram_message,
        'parse_mode': 'HTML'
    }
    
    print(f"  Sending to user: {telegram_user_id}")
    
    response = requests.post(url, json=data, timeout=10)
    
    if response.status_code == 200 and response.json().get('ok'):
        print("[OK] Message sent to Telegram successfully!")
        print(f"  Status: {response.status_code}")
        
        # Save summary
        summary = {
            'timestamp': datetime.now().isoformat(),
            'status': 'success',
            'user_id': telegram_user_id,
            'prediction_image': Path(prediction_img).name,
            'graph_image': Path(graph_img).name,
            'analysis_preview': analysis[:200] + '...' if len(analysis) > 200 else analysis,
            'telegram_response': response.status_code
        }
        
        summary_path = project_root / 'backend' / 'data' / 'telegram_notification_summary.json'
        with open(summary_path, 'w', encoding='utf-8') as f:
            json.dump(summary, f, ensure_ascii=False, indent=2)
        
        print(f"[OK] Summary saved to: {summary_path}")
        
    else:
        print(f"[ERROR] Failed to send to Telegram")
        print(f"  Status: {response.status_code}")
        print(f"  Response: {response.text}")
        sys.exit(1)

except Exception as e:
    print(f"[ERROR] {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

print("\n" + "="*80)
print("[OK] Analysis sent to Telegram successfully!")
print("="*80)
sys.exit(0)
