#!/usr/bin/env python3
"""
Send Gemini Analysis to Both LINE and Telegram
Unified broadcaster for dual-platform signal delivery
"""

import os
import sys
import json
import requests
from pathlib import Path
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed

# Get project root
project_root = Path(__file__).parent.parent
predictions_dir = project_root / 'backend' / 'data' / 'predictions'
graphs_dir = project_root / 'backend' / 'data' / 'graphs'

print("="*80)
print("XAUUSD Trading Analysis - Dual Platform Broadcaster")
print("="*80)

print("\n[0] Loading configuration...")
try:
    from dotenv import load_dotenv
    dotenv_path = project_root / '.env'
    load_dotenv(dotenv_path)
except Exception as e:
    print(f"[WARNING] {e}")

# Step 1: Get Gemini analysis
print("\n[1] Getting Gemini AI analysis...")
try:
    from gemini_api_price_prediction import main as gemini_main
    
    # Find latest images
    prediction_files = sorted(predictions_dir.glob('xauusd_prediction_*.png'), key=lambda x: x.stat().st_mtime, reverse=True)
    graph_files = sorted(graphs_dir.glob('xauusd_graph_*.png'), key=lambda x: x.stat().st_mtime, reverse=True)
    
    if not prediction_files or not graph_files:
        print("[ERROR] Images not found")
        sys.exit(1)
    
    prediction_img = str(prediction_files[0])
    graph_img = str(graph_files[0])
    
    print(f"[OK] Using prediction: {Path(prediction_img).name}")
    print(f"[OK] Using graph: {Path(graph_img).name}")
    
    analysis = gemini_main(prediction_img, graph_img)
    
    if not analysis:
        print("[ERROR] Failed to get Gemini analysis")
        sys.exit(1)
    
    print("[OK] Received Gemini analysis")
    
except Exception as e:
    print(f"[ERROR] {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

# Step 2: Send to LINE
def send_to_line(analysis_text):
    """Send analysis to LINE"""
    try:
        print("\n[2a] Sending to LINE...")
        
        line_token = os.getenv('LINE_CHANNEL_ACCESS_TOKEN')
        line_user_id = os.getenv('LINE_USER_ID')
        use_broadcast = os.getenv('USE_BROADCAST', 'true').lower() == 'true'
        
        if not line_token:
            print("  [SKIP] LINE_CHANNEL_ACCESS_TOKEN not set")
            return {'platform': 'LINE', 'status': 'skipped', 'reason': 'No token'}
        
        # Prepare message
        line_message = f"""XAUUSD Daily Trading Analysis
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{analysis_text}

---
Generated by: AI Trading Bot
Disclaimer: This analysis is based on historical data and may not reflect future price movements"""
        
        messages = [{'type': 'text', 'text': line_message}]
        
        # Send as Push or Broadcast
        if line_user_id and not use_broadcast:
            url = 'https://api.line.me/v2/bot/message/push'
            data = {'to': line_user_id, 'messages': messages}
            print(f"  Sending to user: {line_user_id}")
        else:
            url = 'https://api.line.me/v2/bot/message/broadcast'
            data = {'messages': messages}
            print("  Sending as Broadcast")
        
        headers = {
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {line_token}'
        }
        
        response = requests.post(url, json=data, headers=headers, timeout=10)
        
        if response.status_code == 200:
            print("  [OK] LINE message sent successfully!")
            
            # Save summary
            summary = {
                'timestamp': datetime.now().isoformat(),
                'status': 'success',
                'method': 'broadcast' if use_broadcast else 'push',
                'line_response': response.status_code
            }
            
            summary_path = project_root / 'backend' / 'data' / 'line_notification_summary.json'
            with open(summary_path, 'w', encoding='utf-8') as f:
                json.dump(summary, f, ensure_ascii=False, indent=2)
            
            return {'platform': 'LINE', 'status': 'success'}
        else:
            print(f"  [ERROR] LINE failed: {response.status_code}")
            return {'platform': 'LINE', 'status': 'failed', 'code': response.status_code}
            
    except Exception as e:
        print(f"  [ERROR] LINE exception: {e}")
        return {'platform': 'LINE', 'status': 'error', 'error': str(e)}

# Step 3: Send to Telegram
def send_to_telegram(analysis_text):
    """Send analysis to Telegram"""
    try:
        print("\n[2b] Sending to Telegram...")
        
        telegram_token = os.getenv('TELEGRAM_BOT_TOKEN')
        telegram_user_id = os.getenv('TELEGRAM_USER_ID')
        telegram_enabled = os.getenv('TELEGRAM_ENABLED', 'true').lower() == 'true'
        
        if not telegram_enabled:
            print("  [SKIP] Telegram disabled in configuration")
            return {'platform': 'Telegram', 'status': 'skipped', 'reason': 'Disabled'}
        
        if not telegram_token:
            print("  [SKIP] TELEGRAM_BOT_TOKEN not set")
            return {'platform': 'Telegram', 'status': 'skipped', 'reason': 'No token'}
        
        if not telegram_user_id:
            print("  [SKIP] TELEGRAM_USER_ID not set")
            return {'platform': 'Telegram', 'status': 'skipped', 'reason': 'No user ID'}
        
        # Prepare message with HTML formatting
        telegram_message = f"""<b>📊 XAUUSD Daily Trading Analysis</b>
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{analysis_text}

---
<i>Generated by: AI Trading Bot
Disclaimer: This analysis is based on historical data and may not reflect future price movements</i>"""
        
        url = f'https://api.telegram.org/bot{telegram_token}/sendMessage'
        data = {
            'chat_id': telegram_user_id,
            'text': telegram_message,
            'parse_mode': 'HTML'
        }
        
        print(f"  Sending to user: {telegram_user_id}")
        
        response = requests.post(url, json=data, timeout=10)
        
        if response.status_code == 200 and response.json().get('ok'):
            print("  [OK] Telegram message sent successfully!")
            
            # Save summary
            summary = {
                'timestamp': datetime.now().isoformat(),
                'status': 'success',
                'user_id': telegram_user_id,
                'telegram_response': response.status_code
            }
            
            summary_path = project_root / 'backend' / 'data' / 'telegram_notification_summary.json'
            with open(summary_path, 'w', encoding='utf-8') as f:
                json.dump(summary, f, ensure_ascii=False, indent=2)
            
            return {'platform': 'Telegram', 'status': 'success'}
        else:
            print(f"  [ERROR] Telegram failed: {response.status_code}")
            return {'platform': 'Telegram', 'status': 'failed', 'code': response.status_code}
            
    except Exception as e:
        print(f"  [ERROR] Telegram exception: {e}")
        return {'platform': 'Telegram', 'status': 'error', 'error': str(e)}

# Step 4: Send to both platforms in parallel
print("\n[2] Broadcasting to both platforms...")

results = []
with ThreadPoolExecutor(max_workers=2) as executor:
    futures = {
        executor.submit(send_to_line, analysis): 'LINE',
        executor.submit(send_to_telegram, analysis): 'Telegram'
    }
    
    for future in as_completed(futures):
        result = future.result()
        results.append(result)

# Step 5: Report results
print("\n" + "="*80)
print("BROADCAST SUMMARY")
print("="*80)

success_count = 0
for result in results:
    platform = result['platform']
    status = result['status']
    
    if status == 'success':
        print(f"✅ {platform}: SUCCESS")
        success_count += 1
    elif status == 'skipped':
        print(f"⏭️  {platform}: SKIPPED - {result.get('reason', 'Unknown')}")
    else:
        print(f"❌ {platform}: FAILED - {result.get('error', result.get('code', 'Unknown'))}")

print("="*80)

if success_count > 0:
    print(f"\n[OK] Successfully sent to {success_count}/{len(results)} platforms")
    sys.exit(0)
else:
    print("\n[WARNING] No platforms received the message")
    sys.exit(1)
