#!/usr/bin/env python3
"""
Quick Test - Send to Both LINE and Telegram
ทดสอบส่งข้อความไปทั้ง 2 แพลตฟอร์มโดยไม่ต้องรอ AI วิเคราะห์
"""

import os
import requests
from pathlib import Path
from datetime import datetime

# Get project root
project_root = Path(__file__).parent.parent

print("="*80)
print("Quick Test - Dual Platform Broadcasting")
print("="*80)

# Load environment variables
try:
    from dotenv import load_dotenv
    dotenv_path = project_root / '.env'
    load_dotenv(dotenv_path)
    print("[OK] Loaded .env configuration")
except Exception as e:
    print(f"[WARNING] {e}")

# Test message
test_analysis = """📊 แนวโน้ม: ขาขึ้น (Bullish)

🎯 Signal: BUY
💰 ราคาปัจจุบัน: $2,850.50
🎯 Take Profit: $2,870.00
🛡️ Stop Loss: $2,840.00

📈 Technical Score: 75%
📰 News Score: 68%

⚠️ นี่คือข้อความทดสอบระบบ"""

# Send to LINE
print("\n[1] Testing LINE...")
try:
    line_token = os.getenv('LINE_CHANNEL_ACCESS_TOKEN')
    use_broadcast = os.getenv('USE_BROADCAST', 'true').lower() == 'true'
    
    if not line_token:
        print("  ⏭️ SKIP: LINE_CHANNEL_ACCESS_TOKEN not set")
    else:
        message = f"""XAUUSD Trading Analysis - TEST
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{test_analysis}

---
Generated by: AI Trading Bot (TEST MODE)"""
        
        messages = [{'type': 'text', 'text': message}]
        
        if use_broadcast:
            url = 'https://api.line.me/v2/bot/message/broadcast'
            data = {'messages': messages}
            print("  📤 Sending as Broadcast...")
        else:
            line_user_id = os.getenv('LINE_USER_ID')
            url = 'https://api.line.me/v2/bot/message/push'
            data = {'to': line_user_id, 'messages': messages}
            print(f"  📤 Sending to user: {line_user_id}...")
        
        headers = {
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {line_token}'
        }
        
        response = requests.post(url, json=data, headers=headers, timeout=10)
        
        if response.status_code == 200:
            print("  ✅ LINE: Success!")
        else:
            print(f"  ❌ LINE: Failed ({response.status_code})")
            print(f"     {response.text}")
            
except Exception as e:
    print(f"  ❌ LINE: Error - {e}")

# Send to Telegram
print("\n[2] Testing Telegram...")
try:
    telegram_token = os.getenv('TELEGRAM_BOT_TOKEN')
    telegram_user_id = os.getenv('TELEGRAM_USER_ID')
    telegram_enabled = os.getenv('TELEGRAM_ENABLED', 'true').lower() == 'true'
    
    if not telegram_enabled:
        print("  ⏭️ SKIP: Telegram disabled")
    elif not telegram_token:
        print("  ⏭️ SKIP: TELEGRAM_BOT_TOKEN not set")
    elif not telegram_user_id:
        print("  ⏭️ SKIP: TELEGRAM_USER_ID not set")
    else:
        message = f"""<b>📊 XAUUSD Trading Analysis - TEST</b>
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{test_analysis}

---
<i>Generated by: AI Trading Bot (TEST MODE)</i>"""
        
        url = f'https://api.telegram.org/bot{telegram_token}/sendMessage'
        data = {
            'chat_id': telegram_user_id,
            'text': message,
            'parse_mode': 'HTML'
        }
        
        print(f"  📤 Sending to user: {telegram_user_id}...")
        
        response = requests.post(url, json=data, timeout=10)
        
        if response.status_code == 200 and response.json().get('ok'):
            print("  ✅ Telegram: Success!")
        else:
            print(f"  ❌ Telegram: Failed ({response.status_code})")
            print(f"     {response.text}")
            
except Exception as e:
    print(f"  ❌ Telegram: Error - {e}")

print("\n" + "="*80)
print("Test completed!")
print("="*80)
